backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]


handler404='main.views.handler404'
handler500='main.views.handler500'
handler403='main.views.handler403'

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name='main'
urlpatterns = [
  path('', views.index, name='index'),
  path('about/', views.about, name='about'),
  path('blog/', views.PostList.as_view(), name='blog'),
  path('blog/<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
  path('services/', views.services, name='services'),
  path('work/', views.work, name='work'),
  path('contact/', views.contact, name='contact'),
  path('send-message/', views.send_message, name='send_message')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
User = get_user_model()


class Category(models.Model):

  name = models.CharField(verbose_name='Наименование категории', max_length=255)

  def __str__(self):
    return f'Категория {self.name}'

  class Meta:
    verbose_name = 'Категорию'
    verbose_name_plural = 'Категории'

class Post(models.Model):

  name = models.CharField(verbose_name='Наименование поста', max_length=255)
  image = models.ImageField(verbose_name='Изображение', upload_to='posts/')
  content = models.TextField(verbose_name='Содержание поста', blank=True, null=True)
  category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
  date = models.DateTimeField(verbose_name='Дата публикации', auto_now_add=True)
  slug = models.SlugField(verbose_name='Наименование поста', unique=True)


  def __str__(self):
    return f'Пост {self.name}'

  def get_absolute_url(self):
    return reverse('post_detail', args=[str(self.slug)])

  class Meta:
    verbose_name = 'Пост'
    verbose_name_plural = 'Посты'


class Case(models.Model):

  name = models.CharField(verbose_name='Наименование кейса', max_length=255)
  image = models.ImageField(verbose_name='Изображение', upload_to='cases/')
  content = models.CharField(verbose_name='Содержание кейса', max_length=255, blank=True, null=True)
  slug = models.SlugField(verbose_name='Наименование кейса', unique=True)


  def __str__(self):
    return f'Кейс {self.name}'

  def get_absolute_url(self):
    return reverse('case_detail', args=[str(self.slug)])

  class Meta:
    verbose_name = 'Кейс'
    verbose_name_plural = 'Кейсы'

main/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import DetailView, ListView
from django.views.decorators.csrf import csrf_exempt
from .models import Post

from telebot import TeleBot

BOT_TOKEN = '6079077575:AAHWKWn6YyBzVjfjxQ0cU2UXCvke9aiERpM'
CHANNEL_ID = -1001652862966


bot = TeleBot(token=BOT_TOKEN, parse_mode='HTML')



def get_client_ip(request):
  x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
  if x_forwarded_for:
    ip = x_forwarded_for.split(',')[0]
  else:
    ip = request.META.get('REMOTE_ADDR')
  return ip


def is_ajax(request):
  return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def index(request):
  posts = Post.objects.all().order_by('-date')[:3]
  return render(request, 'main/index.html', context={'posts':posts})

def about(request):
  return render(request, 'main/about.html', context={})

@csrf_exempt
def send_message(request):
  if is_ajax(request):
    dict_data = dict(request.POST)
    number = dict_data.get('number')[0]
    title = dict_data.get('title')[0]
    message = dict_data.get('message')[0]

    bot.send_message(chat_id=CHANNEL_ID, text=f"""
<b>Пришла заявка от пользователя:</b> {number}\n\n
<b>Суть проблемы:</b> {title}\n\n
<b>Услуга:</b> {message}    
""")
    return JsonResponse(data={"result":"success"})


class PostList(ListView):

  model = Post
  template_name = 'main/blog.html'

class PostDetail(DetailView):

  model = Post
  template_name = 'main/blog-detail.html'

def contact(request):
  return render(request, 'main/contact.html', context={})

def services(request):
  return render(request, 'main/services.html', context={})

def work(request):
  return render(request, 'main/work.html', context={})



def handler404(request, *args, **argv):
  return redirect('/')

def handler500(request, *args, **argv):
  return render(request, 'main/500.html', context={})

def handler403(request, *args, **argv):
  return render(request, 'main/403.html', context={})

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}
{%block title %}Art Nygma About - О компании Art Nygma {%endblock%}
{% block content %}
		<div id="colorlib-main">

			<div class="colorlib-about">
				<div class="colorlib-narrow-content">
					<div class="row row-bottom-padded-md">
						<div class="col-md-6">
							<div class="about-img animate-box" data-animate-effect="fadeInLeft" style="background-image: url({% static 'images/img_bg_2.jpg' %});">
							</div>
						</div>
						<div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
							<div class="about-desc">
								<span class="heading-meta">ArtNygma</span>
								<h2 class="colorlib-heading">Быстроразвивающаяся компания в Тюмени</h2>
								<p>Создание корпусной и мягкой мебели для вашего дома по высоким стандартам качества. Мебель на заказ по индивидуальным проектам с учетом всех пожеланий заказчика. 
								</p>
								<p></p>
							</div>
							<div class="row padding">
								<div class="col-md-4 no-gutters animate-box" data-animate-effect="fadeInLeft">
									<a href="#" class="steps active">
										<p class="icon"><span><i class="icon-check"></i></span></p>
										<h3>Короткие сроки 
											<br></h3>
									</a>
								</div>
								<div class="col-md-4 no-gutters animate-box" data-animate-effect="fadeInLeft">
									<a href="#" class="steps">
										<p class="icon"><span><i class="icon-check"></i></span></p>
										<h3>Высокое качество работ<br></h3>
									</a>
								</div>
								<div class="col-md-4 no-gutters animate-box" data-animate-effect="fadeInLeft">
									<a href="#" class="steps">
										<p class="icon"><span><i class="icon-check"></i></span></p>
										<h3>Учёт индивидуальных предпочтений<br></h3>
									</a>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4 animate-box" data-animate-effect="fadeInLeft">
							<h2 class="colorlib-heading">ArtNygma</h2>
							<p>текст.</p>
						</div>
						<div class="col-md-8 animate-box" data-animate-effect="fadeInRight">
							<div class="fancy-collapse-panel">
								<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
									<div class="panel panel-default">
									    <div class="panel-heading" role="tab" id="headingOne">
									        <h4 class="panel-title">
									            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Почему нас выбирают?
									            </a>
									        </h4>
									    </div>
									    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
									         <div class="panel-body">
									            <div class="row">
										      		<div class="col-md-6">
										      			<p>Нашу положительную репутацию мы заслужили высоким качеством изделий и индивидуальным подходом к каждому клиенту</p>
										      		</div>
										      		<div class="col-md-6">
										      			<p></p>
										      		</div>
										      	</div>
									         </div>
									    </div>
									</div>
									<div class="panel panel-default">
									    <div class="panel-heading" role="tab" id="headingTwo">
									        <h4 class="panel-title">
									            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Что мы делаем?
									            </a>
									        </h4>
									    </div>
									    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
									        <div class="panel-body">
									            <p>Индивидуальную мебель с учётом всех пожеланий клиента<strong></strong>,</p>
													<ul>
														<li>Корпусную</li>
														<li>Мягкую</li>
													</ul>
									        </div>
									    </div>
									</div>
									<div class="panel panel-default">
									    <div class="panel-heading" role="tab" id="headingThree">
									        <h4 class="panel-title">
									            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">Специализация
									            </a>
									        </h4>
									    </div>
									    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
									        <div class="panel-body">
									            <p>Работа с ЛДСП, МДФ, HPL пластиком, Искусственным камнем
													Распил, облицовывание деталей кромкой, присадка деталей, сборка изделий, составление проектов<strong></strong>, </p>	
									        </div>
									    </div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			
			<div id="colorlib-counter" class="colorlib-counters" style="background-image: url({% static 'images/cover_bg_1.jpg' %});" data-stellar-background-ratio="0.5">
				<div class="overlay"></div>
				<div class="colorlib-narrow-content">
					<div class="row">
					</div>
					<div class="row">
						<div class="col-md-3 text-center animate-box">
							<span class="icon"><i class="flaticon-skyline"></i></span>
							<span class="colorlib-counter js-counter" data-from="0" data-to="1539" data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Кейсы</span>
						</div>
						<div class="col-md-3 text-center animate-box">
							<span class="icon"><i class="flaticon-engineer"></i></span>
							<span class="colorlib-counter js-counter" data-from="0" data-to="3653" data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Заказчики</span>
						</div>
						<div class="col-md-3 text-center animate-box">
							<span class="icon"><i class="flaticon-architect-with-helmet"></i></span>
							<span class="colorlib-counter js-counter" data-from="0" data-to="5987" data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Констркутор</span>
						</div>
						<div class="col-md-3 text-center animate-box">
							<span class="icon"><i class="flaticon-worker"></i></span>
							<span class="colorlib-counter js-counter" data-from="0" data-to="3999" data-speed="5000" data-refresh-interval="50"></span>
							<span class="colorlib-counter-label">Партнеры</span>
						</div>
					</div>
				</div>
			</div>

			<div id="get-in-touch" class="colorlib-bg-color">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
							<h2>Заказать услугу!</h2>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
							<p class="colorlib-lead">Для подробной реализации вашей идеи, свяжитесь с нами.</p>
							<p><a href="{% url 'main:contact' %}" class="btn btn-primary btn-learn">Написать!</a></p>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	{%endblock%}

main/templates/main/base.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{%block title %}{%endblock%}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="{% static 'favicon.ico' %}">

	<link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
	<!-- Flaticons  -->
	<link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js"></script>
	<![endif]-->


	</head>
	<body>
	<div id="colorlib-page">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
		<aside id="colorlib-aside" role="complementary" class="border js-fullheight">
			<h1 id="colorlib-logo"><a href="{% url 'main:index' %}">ArtNygma</a></h1>
			<nav id="colorlib-main-menu" role="navigation">
				<ul>
					<li><a href="{% url 'main:index' %}">Главная</a></li>
					<li><a href="{% url 'main:work' %}">Кейсы</a></li>
					<li><a href="{% url 'main:about' %}">О нас</a></li>
					<li><a href="{% url 'main:services' %}">Сервисы</a></li>
					<li><a href="{% url 'main:blog' %}">Блог</a></li>
					<li><a href="{% url 'main:contact' %}">Контакты</a></li>
				</ul>
			</nav>

			<div class="colorlib-footer">
				<p	><small>Разработано:</small> <a href="https://belofflab.com/vpn/" target="_blank">Beloff Laboratory</a></p>
				<p><small>&copy;
Copyright &copy;<script>document.write(new Date().getFullYear());</script> Все права защищены
 </span> </small></p>
				<ul>
					<li><a href="https://instagram.com/artnygma72" target="_blank"><i class="icon-instagram"></i></a></li>
					<li><a href="https://vk.com/artnygma" target="_blank"><i class="icon-vk"></i></a></li>
				</ul>
			</div>

		</aside>
      {% block content %}
      {% endblock %}
    </div>



  <!-- jQuery -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- jQuery Easing -->
  <script type="text/javascript" src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <!-- Bootstrap -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- Waypoints -->
  <script type="text/javascript" src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <!-- Flexslider -->
  <script type="text/javascript" src="{% static 'js/jquery.flexslider-min.js' %}"></script>
  <!-- Sticky Kit -->
  <script type="text/javascript" src="{% static 'js/sticky-kit.min.js' %}"></script>
  <!-- Owl carousel -->
  <script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
  <!-- Counters -->
  <script type="text/javascript" src="{% static 'js/jquery.countTo.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/notify.js'%}"></script>


  <!-- MAIN JS -->
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/sender.js' %}"></script>
  </body>
</html>

main/templates/main/blog-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Detail</title>
</head>
<body>
  Detail
</body>
</html>

main/templates/main/blog.html
{% extends 'main/base.html' %}
{% load static %}
{%block title %}Art Nygma - Блог компании Art Nygma {%endblock%}
{% block content %}

		<div id="colorlib-main">

			<div class="colorlib-blog">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
							<span class="heading-meta">Блог</span>
							<h2 class="colorlib-heading">Читайте наш блог</h2>
						</div>
					</div>
					<div class="row">
						{% for post in object_list %}
						<div class="col-md-4 col-sm-6 animate-box" data-animate-effect="fadeInLeft">
							<div class="blog-entry">
								<a href="{% url 'main:blog' %}" class="blog-img"><img src="{{post.image.url}}" class="img-responsive" alt="HTML5 Bootstrap Template by colorlib.com"></a>
								<div class="desc">
									<span><small>{{post.date}} </small> | <small> {{post.category.name}}</small> | <small> <i class="icon-bubble3"></i> 4</small></span>
									<h3><a href="{% url 'main:blog' %}">{{post.name}}</a></h3>
									<p>{{post.description}}</p>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>

					<div class="row">
						<div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">
							<ul class="pagination">
								<li class="disabled"><a href="#">&laquo;</a></li>
								<li class="active"><a href="#">1</a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#">&raquo;</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div id="get-in-touch" class="colorlib-bg-color">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
							<h2>Заказать услугу!</h2>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
							<p class="colorlib-lead">Для подробной реализации вашей идеи, свяжитесь с нами.</p>
							<p><a href="{% url 'main:contact' %}" class="btn btn-primary btn-learn">Написать!</a></p>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	{%endblock%}

main/templates/main/contact.html
{% extends 'main/base.html' %}
{%block title %}Art Nygma Contact - Контакты компании Art Nygma {%endblock%}
	{%block content %}
		<div id="colorlib-main">

			<div class="colorlib-contact">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">
							<span class="heading-meta">Читать</span>
							<h2 class="colorlib-heading">Получить консультацию 
							</h2>
						</div>
					</div>
					<div class="row">
						<div class="col-md-5">
							<div class="colorlib-feature colorlib-feature-sm animate-box" data-animate-effect="fadeInLeft">
								<div class="colorlib-icon">
									<i class="icon-globe-outline"></i>
								</div>
								<div class="colorlib-text">
									<p><a href="#">artnygma72@mail.ru</a></p>
								</div>
							</div>

							<div class="colorlib-feature colorlib-feature-sm animate-box" data-animate-effect="fadeInLeft">
								<div class="colorlib-icon">
									<i class="icon-map"></i>
								</div>
								<div class="colorlib-text">
									<p>Россия, г. Тюмень</p>
								</div>
							</div>

							<div class="colorlib-feature colorlib-feature-sm animate-box" data-animate-effect="fadeInLeft">
								<div class="colorlib-icon">
									<i class="icon-phone"></i>
								</div>
								<div class="colorlib-text">
									<p><a href="tel://+79829407490">+7 (982) 940-74-90</a></p>
								</div>
							</div>
						</div>
						<div class="col-md-7 col-md-push-1">
							<div class="row">
								<div class="col-md-10 col-md-offset-1 col-md-pull-1 animate-box" data-animate-effect="fadeInLeft">
									<form action="">
										<div class="form-group">
											<input id="formName" type="text" class="form-control" placeholder="Наименование" required>
										</div>
										<div class="form-group">
											<input id="formNumber" type="text" class="form-control" placeholder="Ваш номер телефона" required>
										</div>
										<div class="form-group">
											<textarea id="formText" name="" id="message" cols="30" rows="7" class="form-control" placeholder="Какая услуга вас интересует?" required></textarea>
										</div>
										<div class="form-group">
											<input class="btn btn-primary btn-send-message" value="Отправить">
										</div>
									</form>
								</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>

			<div id="map"></div>	

			<div id="get-in-touch" class="colorlib-bg-color">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
							<h2>Заказать услугу!</h2>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
							<p class="colorlib-lead">Для подробной реализации вашей идеи, свяжитесь с нами.</p>
							<p><a href="#" class="btn btn-primary btn-learn">Написать!</a></p>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	{%endblock%}

main/templates/main/services.html
{% extends 'main/base.html' %}
{%block title %}Art Nygma Services - Сервисы компании Art Nygma {%endblock%}
	{%block content%}
		<div id="colorlib-main">
			<div class="colorlib-services">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
							<span class="heading-meta">Сервисы</span>
							<h2 class="colorlib-heading">ArtNygma</h2>
						</div>
					</div>
					<div class="row row-bottom-padded-md">
						<div class="col-md-6">
							<div class="row">
								<div class="col-md-12">
									<div class="colorlib-feature animate-box" data-animate-effect="fadeInLeft">
										<div class="colorlib-icon">
											<i class="flaticon-worker"></i>
										</div>
										<div class="colorlib-text">
											<h3>Создание проекта мебели</h3>
											<p>Спроектируем вашу мебель и посчитаем стоимость

											</p>
										</div>
									</div>

									<div class="colorlib-feature animate-box" data-animate-effect="fadeInLeft">
										<div class="colorlib-icon">
											<i class="flaticon-sketch"></i>
										</div>
										<div class="colorlib-text">
											<h3>Технологический расчёт</h3>
											<p>Произведём технологический расчёт изделия в программе «Базис-Мебельщик»
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="row">
								<div class="col-md-12">
									<div class="colorlib-feature animate-box" data-animate-effect="fadeInLeft">
										<div class="colorlib-icon">
											<i class="flaticon-engineering"></i>
										</div>
										<div class="colorlib-text">
											<h3>Распил</h3>
											<p>Сделаем детали из ЛДСП, МДФ, ХДФ или ДВП по вашим размерам </p>
										</div>
									</div>

									<div class="colorlib-feature animate-box" data-animate-effect="fadeInLeft">
										<div class="colorlib-icon">
											<i class="flaticon-crane"></i>
										</div>
										<div class="colorlib-text">
											<h3>Монтаж</h3>
											<p>Быстрый и профессиональный монтаж ваших изделий</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- <div class="row">
						<div class="col-md-4">
							<a href="services.html" class="services-wrap animate-box" data-animate-effect="fadeInRight">
								<div class="services-img" style="background-image: url(images/services-1.jpg)"></div>
								<div class="desc">
									<h3>Design &amp; Build</h3>
								</div>
							</a>
						</div>
						<div class="col-md-4">
							<a href="services.html" class="services-wrap animate-box" data-animate-effect="fadeInRight">
								<div class="services-img" style="background-image: url(images/services-2.jpg)"></div>
								<div class="desc">
									<h3>фыв фыв</h3>
								</div>
							</a>
						</div>
						<div class="col-md-4">
							<a href="services.html" class="services-wrap animate-box" data-animate-effect="fadeInRight">
								<div class="services-img" style="background-image: url(images/services-3.jpg)"></div>
								<div class="desc">
									<h3>фыв фыв</h3>
								</div>
							</a>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4">
							<a href="services.html" class="services-wrap animate-box" data-animate-effect="fadeInRight">
								<div class="services-img" style="background-image: url(images/services-4.jpg)"></div>
								<div class="desc">
									<h3>Painting &amp; Tiling</h3>
								</div>
							</a>
						</div>
						<div class="col-md-4">
							<a href="services.html" class="services-wrap animate-box" data-animate-effect="fadeInRight">
								<div class="services-img" style="background-image: url(images/services-5.jpg)"></div>
								<div class="desc">
									<h3>Kitchen Remodeling</h3>
								</div>
							</a>
						</div>
					</div> -->
				</div>
			</div>

			<div id="get-in-touch" class="colorlib-bg-color">
				<div class="colorlib-narrow-content">
					<div class="row">
						<div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
							<h2>Заказать услугу!</h2>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
							<p class="colorlib-lead">Для подробной реализации вашей идеи, свяжитесь с нами.</p>
							<p><a href="{% url 'main:contact' %}" class="btn btn-primary btn-learn">Написать!</a></p>
						</div>
						
					</div>
				</div>
			</div>
		</div>
{%endblock%}